spring:
  application:
    name: reto-aws-users

  datasource:
    url: jdbc:postgresql://reto-aws-postgres.c81w4ge4st5v.us-east-1.rds.amazonaws.com:5432/retoawspostgres
    username: camidev
    password: Admin123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: logs/application.log
  level:
    root: info
    org.springframework: info
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace